Func init added
Merteg/pl-health-service pull request #5
Opened 2023-02-22 21:05 UTC by JuanC1303

I added the func init.

This function start the conecction with the mongo data base and try to connect to the collections that we will use. If the collections does not exist the program will create the collection.

2023-02-23 13:50 UTC, Merteg commented on main.go
> +const mongoURI string = "mongodb+srv://admin:admin@pl-health-service.s25udti.mongodb.net/test"
Note: it's gonna work even without type specification

2023-02-23 13:50 UTC, Merteg commented on main.go
> +	targetCollection, err := client.Database("pl-health-service").ListCollectionNames(context.TODO(), bson.M{"name": "target"})
you defined ctx on line 26. You should use it instead of context.TODO

2023-02-23 13:50 UTC, Merteg commented on main.go
> +		_ = client.Database("pl-health-service").CreateCollection(context.TODO(), "target")
Why do you ignore the error?

2023-02-23 13:50 UTC, Merteg commented on main.go
> +	targetCollection, err := client.Database("pl-health-service").ListCollectionNames(context.TODO(), bson.M{"name": "target"})
Create a constant for database name pls
Also for collection name
Note that collection names should be 'targets' and 'health'

2023-02-23 13:50 UTC, Merteg commented on main.go
> +		log.Info().Msg("target collection ready")
Better to say "exist" not "ready"

2023-02-23 13:50 UTC, Merteg commented on main.go
> +		_ = client.Database("pl-health-service").CreateCollection(context.TODO(), "health")
same here. Handle error, don't ignore it

2023-02-23 14:51 UTC, Merteg requested changes
coll1 and coll2 is not cool)
Also you can wrap list of constants under single const ()

2023-02-23 14:51 UTC, Merteg commented on main.go
> +const coll2 = "health"
```suggestion
const (
    port = "localhost:8080"
    mongoURI = "mongodb+srv://admin:admin@pl-health-service.s25udti.mongodb.net/test"
    dbName = "pl-health-service"
    targetsCollName = "targets"
    healthCollName = "health"
)
```

2023-02-23 15:52 UTC, Merteg approved these changes

2023-02-28 14:09 UTC, crismxiex approved these changes

2023-02-28 14:09 UTC, merged